const GET_CONTACTS = "GET_CONTACTS";
const DELETE_CONTACT = "DELETE_CONTACT";
const ADD_CONTACT = "ADD_CONTACT";
const SEARCH_CONTACT = "SEARCH_CONTACT";
const UPDATE_CONTACT = "UPDATE_CONTACT";

export { GET_CONTACTS, DELETE_CONTACT, ADD_CONTACT, SEARCH_CONTACT, UPDATE_CONTACT };